spring:
  application:
    name: admin

---
spring:
  profiles: dev
info:
  describe: '1234567'

---
spring:
  profiles: prod
info:
  describe: '{cipher}adbbbeebb0f9053ab0bde82b8c74dc1d2495309273993b0ccac326fb50424a5a'